import { NextResponse } from 'next/server';
import { requireContext } from '@/lib/auth';
import { instant } from '@/lib/domain/calculations';
import { z } from 'zod';
const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'private, no-store'}});
const date=z.iso.date(),time=z.string().regex(/^\d{2}:\d{2}$/),uuid=z.uuid();
const booking=z.object({id:uuid.optional(),client_id:uuid,staff_id:uuid,service_id:uuid,branch_id:uuid,day:date,time,duration:z.coerce.number().int().min(5).max(720),price_minor:z.number().int().min(0).max(999999999999),notes:z.string().max(4000).default(''),updated_at:z.string().optional()});
export async function POST(request:Request){try{
 if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'Недопустимый источник.'},403);
 const ctx=await requireContext();const {operation,values}=z.object({operation:z.string(),values:z.unknown()}).parse(await request.json());const {db,organization,user}=ctx;const org=organization.id;
 const finish=async(q:PromiseLike<{error:{code?:string;message:string}|null;data:unknown}>)=>{const {data,error}=await q;if(error){const messages:Record<string,string>={no_staff_overlap:'Это время уже занято. Выберите другое окно.',outside_schedule:'Запись должна быть внутри рабочей смены.',terminal_appointment:'Завершённую или отменённую запись менять нельзя.',invalid_status_transition:'Недопустимый переход статуса.',service_not_assigned:'Услуга не назначена сотруднику.',last_owner:'Нельзя убрать последнего владельца.',schedule_conflict:'Смена конфликтует с существующими записями.',payment_exceeds_balance:'Сумма превышает неоплаченный остаток.',payment_appointment_required:'Выберите запись.'};const key=Object.keys(messages).find(k=>error.message.includes(k));return json({error:key?messages[key]:error.code==='23P01'?'Это время уже занято.':error.code==='PGRST116'?'Данные изменились или объект недоступен. Обновите страницу.':'Не удалось сохранить. Проверьте связи, права и текущий статус.'},409);}return json({record:data});};
 if(operation==='schedule'){const v=z.object({staff_id:uuid,work_date:date,starts_local:time,ends_local:time}).parse(values);if(v.ends_local<=v.starts_local)return json({error:'Конец смены должен быть позже начала.'},400);return finish(db.from('staff_schedules').upsert({...v,organization_id:org},{onConflict:'staff_id,work_date'}).select().single());}
 if(operation==='assignment'){const v=z.object({staff_id:uuid,service_id:uuid,enabled:z.boolean()}).parse(values);return finish(v.enabled?db.from('staff_services').upsert({staff_id:v.staff_id,service_id:v.service_id,organization_id:org},{onConflict:'staff_id,service_id'}).select().single():db.from('staff_services').delete().eq('organization_id',org).eq('staff_id',v.staff_id).eq('service_id',v.service_id).select());}
 if(operation==='booking'){const v=booking.parse(values);const starts_at=instant(v.day,v.time,organization.timezone),ends_at=new Date(new Date(starts_at).getTime()+v.duration*60000).toISOString();const payload={client_id:v.client_id,staff_id:v.staff_id,service_id:v.service_id,branch_id:v.branch_id,starts_at,ends_at,price_minor:v.price_minor,notes:v.notes};if(v.id){if(!v.updated_at)return json({error:'Обновите запись перед изменением.'},409);return finish(db.from('appointments').update(payload).eq('organization_id',org).eq('id',v.id).eq('updated_at',v.updated_at).select().single());}return finish(db.from('appointments').insert({...payload,organization_id:org,created_by:user.id}).select().single());}
 if(operation==='status'){const v=z.object({id:uuid,status:z.enum(['confirmed','checked_in','completed','cancelled','no_show']),updated_at:z.string()}).parse(values);return finish(db.from('appointments').update({status:v.status}).eq('organization_id',org).eq('id',v.id).eq('updated_at',v.updated_at).select().single());}
 if(operation==='payment'){
  const v=z.object({appointment_id:uuid,amount_minor:z.number().int().positive().max(999999999999),method:z.enum(['cash','card','transfer']),status:z.enum(['pending','paid']),idempotency_key:uuid}).parse(values);
  const previous=await db.from('payments').select('*').eq('organization_id',org).eq('idempotency_key',v.idempotency_key).maybeSingle();
  if(previous.error)return json({error:'Не удалось проверить повторный платёж.'},503);
  const replay=(p:Record<string,unknown>)=>p.appointment_id===v.appointment_id&&Number(p.amount_minor)===v.amount_minor&&p.method===v.method ? json({record:p,replayed:true}) : json({error:'Этот запрос уже использован для другого платежа. Откройте новую форму.'},409);
  if(previous.data)return replay(previous.data);
  const result=await db.from('payments').insert({...v,organization_id:org}).select().single();
  if(result.error){const raced=await db.from('payments').select('*').eq('organization_id',org).eq('idempotency_key',v.idempotency_key).maybeSingle();if(raced.data)return replay(raced.data);}
  return finish(Promise.resolve(result));
 }
 if(operation==='payment_status'){const v=z.object({id:uuid,status:z.enum(['paid','refunded','void'])}).parse(values);return finish(db.from('payments').update({status:v.status}).eq('organization_id',org).eq('id',v.id).select().single());}
 if(operation==='profile'){const v=z.object({first_name:z.string().trim().min(1).max(120),last_name:z.string().trim().max(120)}).parse(values);return finish(db.from('app_users').update(v).eq('id',user.id).select('id').single());}
 if(ctx.member.role!=='owner')return json({error:'Требуется роль owner.'},403);
 if(operation==='organization'){const v=z.object({name:z.string().trim().min(2).max(120),timezone:z.string().max(80).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}})}).parse(values);return finish(db.from('organizations').update(v).eq('id',org).select().single());}
 if(operation==='member'){const v=z.object({telegram_user_id:z.string().regex(/^\d{1,16}$/),role:z.enum(['owner','admin','specialist'])}).parse(values);const {data:account,error}=await db.from('app_users').select('id').eq('telegram_user_id',v.telegram_user_id).single();if(error)return json({error:'Пользователь должен сначала открыть приложение из Telegram.'},400);return finish(db.from('organization_members').upsert({organization_id:org,user_id:account.id,role:v.role}).select().single());}
 if(operation==='member_role'){const v=z.object({user_id:uuid,role:z.enum(['owner','admin','specialist'])}).parse(values);return finish(db.from('organization_members').update({role:v.role}).eq('organization_id',org).eq('user_id',v.user_id).select().single());}
 return json({error:'Неизвестная операция.'},400);
 }catch(e){return json({error:e instanceof z.ZodError?'Проверьте обязательные поля и формат данных.':e instanceof Error?e.message:'Операция недоступна.'},400);}}
