'use client';
import { useState } from 'react';
import { PageHeading } from '@/components/page-heading';
import { Empty, Field, Form, Gate, Sheet, mutate, useWorkspace } from './shared';
import { ClientFields } from './clients';
import { freeSlots, localDay, localTime, money, minor, shiftDay, statusLabels } from '@/lib/domain/calculations';
import type { Appointment, Workspace, Status } from '@/lib/domain/types';
const transitions:Record<Status,Status[]>={pending:['confirmed','cancelled','no_show'],confirmed:['checked_in','cancelled','no_show'],checked_in:['completed','cancelled'],completed:[],cancelled:[],no_show:[]};
export function Booking({w,a,day,onSaved}:{w:Workspace;a?:Appointment;day:string;onSaved:()=>Promise<void>}){
 const [date,setDate]=useState(a?localDay(a.starts_at,w.organization.timezone):day),[service,setService]=useState(a?.service_id||''),[staff,setStaff]=useState(a?.staff_id||''),[branch,setBranch]=useState(a?.branch_id||''),[duration,setDuration]=useState(a?Math.round((+new Date(a.ends_at)-+new Date(a.starts_at))/60000):60),[price,setPrice]=useState(a?String(a.price_minor/100):''),[time,setTime]=useState(a?localTime(a.starts_at,w.organization.timezone):''),[client,setClient]=useState(a?.client_id||(typeof window!=='undefined'?new URLSearchParams(window.location.search).get('client')||'':'')),[newClient,setNewClient]=useState(false),[clients,setClients]=useState(w.clients);
 const slots=freeSlots(w,staff,service,date,duration,a?.id);
 return <><p className="muted">Часовой пояс салона: {w.organization.timezone}</p><Form label={a?'Сохранить изменения':'Создать запись'} onSubmit={async v=>{await mutate({operation:'booking',values:{id:a?.id,updated_at:a?.updated_at,client_id:client,staff_id:staff,service_id:service,branch_id:branch,day:date,time,duration,price_minor:minor(price),notes:v.notes}},'/api/operations');await onSaved();}}>
 <Field label="Клиент" name="client_id"><select required value={client} onChange={e=>setClient(e.target.value)}><option value="">Выберите клиента</option>{clients.filter(c=>!c.archived_at).map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone}</option>)}</select></Field><button className="btn secondary" type="button" onClick={()=>setNewClient(!newClient)}>Создать клиента в записи</button>
 <Field label="Филиал" name="branch_id"><select required value={branch} onChange={e=>{setBranch(e.target.value);setStaff('');setTime('');}}><option value="">Выберите филиал</option>{w.branches.filter(b=>!b.archived_at).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
 <Field label="Услуга" name="service_id"><select required value={service} onChange={e=>{setService(e.target.value);const s=w.services.find(s=>s.id===e.target.value);setDuration(s?.duration_minutes||60);setPrice(String((s?.price_minor||0)/100));setTime('');}}><option value="">Выберите услугу</option>{w.services.filter(s=>s.active&&!s.archived_at).map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration_minutes} мин</option>)}</select></Field>
 <Field label="Сотрудник" name="staff_id"><select required value={staff} onChange={e=>{setStaff(e.target.value);setTime('');}}><option value="">Выберите сотрудника</option>{w.staff.filter(s=>s.active&&!s.archived_at&&s.branch_id===branch&&w.assignments.some(x=>x.staff_id===s.id&&x.service_id===service)).map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></Field>
 <Field label="Дата" name="day"><input type="date" required value={date} onChange={e=>{setDate(e.target.value);setTime('');}}/></Field><Field label="Длительность, минут" name="duration"><input type="number" min="5" max="720" required value={duration} onChange={e=>{setDuration(Number(e.target.value));setTime('');}}/></Field>
 <Field label="Время" name="time"><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field><div><p className="muted">Свободные окна · {duration} мин</p><div className="actions">{slots.map(t=><button type="button" className={`btn ${t===time?'':'secondary'}`} key={t} onClick={()=>setTime(t)}>{t}</button>)}</div>{!slots.length&&<p className="muted">Нет доступных окон. Проверьте смену, назначение услуги или выберите другой день.</p>}</div>
 <Field label={`Цена, ${w.organization.currency}`} name="price"><input required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></Field><Field label="Заметки к записи" name="notes" value={a?.notes} type="textarea" maxLength={4000}/><p className="muted">Окончание рассчитывается автоматически. Сервер повторно проверяет смену и пересечения.</p></Form>
 {newClient&&<section className="crm-card"><h2>Новый клиент</h2><Form label="Создать и выбрать клиента" onSubmit={async v=>{const result=await mutate({table:'clients',values:v});setClients([...clients,result.record]);setClient(result.record.id);setNewClient(false);}}><ClientFields/></Form></section>}</>;
}
export function AppointmentSummary({a,w}:{a:Appointment;w:Workspace}){return <><span className="agenda-time">{localTime(a.starts_at,w.organization.timezone)}<small>{localTime(a.ends_at,w.organization.timezone)}</small></span><span className="grow"><strong>{w.clients.find(c=>c.id===a.client_id)?.full_name||'Клиент'}</strong><span className="muted">{w.services.find(s=>s.id===a.service_id)?.name}</span><span className="muted">{w.staff.find(s=>s.id===a.staff_id)?.display_name}</span><span className={`status status-${a.status}`}>{statusLabels[a.status]}</span></span><span className="money">{money(a.price_minor,w.organization.currency)}</span></>;}
export default function Appointments(){const state=useWorkspace(),[selectedDay,setDay]=useState(''),[filter,setFilter]=useState('');return <><PageHeading title="Записи" eyebrow="Операционный день" description="Ваш день — от первого гостя до последнего визита."/><Gate state={state} operator={false}>{w=>{const day=selectedDay||localDay(new Date(),w.organization.timezone),operator=w.role!=='specialist',rows=w.appointments.filter(a=>localDay(a.starts_at,w.organization.timezone)===day&&(!filter||a.staff_id===filter)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));return <>{operator&&<Sheet title="Новая запись" trigger={<button className="btn">Создать запись</button>}>{close=><Booking w={w} day={day} onSaved={async()=>{close();await state.refresh();}}/>}</Sheet>}<div className="day-control"><button className="btn secondary" aria-label="Предыдущий день" onClick={()=>setDay(shiftDay(day,-1))}>←</button><Field label="День" name="day"><input type="date" value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/></Field><button className="btn secondary" aria-label="Следующий день" onClick={()=>setDay(shiftDay(day,1))}>→</button></div><Field label="Сотрудник" name="staff"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Все сотрудники</option>{w.staff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></Field><p className="muted">{w.organization.timezone} · {rows.length} записей</p><div className="crm-list">{rows.map(a=><Sheet key={a.id} title="Карточка записи" trigger={<button className="crm-card client-card"><AppointmentSummary a={a} w={w}/></button>}>{close=><><div className="crm-card client-card"><AppointmentSummary a={a} w={w}/></div><p className="muted">{a.notes}</p>{operator&&transitions[a.status].length>0&&<><Form label="Изменить статус" onSubmit={async v=>{if((v.status==='cancelled'||v.status==='no_show')&&v.confirm!=='on')throw new Error('Подтвердите отмену или неявку.');await mutate({operation:'status',values:{id:a.id,status:v.status,updated_at:a.updated_at}},'/api/operations');close();await state.refresh();}}><Field label="Новый статус" name="status"><select name="status">{transitions[a.status].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field><label className="check"><input type="checkbox" name="confirm"/>Подтверждаю отмену / неявку, если выбрана</label></Form><h2>Редактирование / перенос</h2><Booking w={w} a={a} day={day} onSaved={async()=>{close();await state.refresh();}}/></>}</>}</Sheet>)}</div>{!rows.length&&<Empty title="Спокойный день, чистое расписание" text="На выбранный день записей пока нет. Создайте первую запись или выберите другую дату."/>}</>;}}</Gate></>;}
