'use client';
import { useState } from 'react';
import Link from 'next/link';
import { PageHeading } from '@/components/page-heading';
import { Archive, Empty, Field, Form, Gate, Sheet, mutate, useWorkspace } from './shared';
import type { Client, Workspace } from '@/lib/domain/types';
import { clientMetrics, localDay, localTime, money, statusLabels } from '@/lib/domain/calculations';
export function ClientFields({client}:{client?:Client}){return <><Field label="Имя клиента" name="full_name" value={client?.full_name} required/><Field label="Телефон" name="phone" type="tel" value={client?.phone}/><Field label="Email" name="email" type="email" value={client?.email}/><Field label="Дата рождения" name="birth_date" type="date" value={client?.birth_date}/><Field label="Заметки" name="notes" type="textarea" maxLength={4000} value={client?.notes}/></>;}
export function History({w,clientId,staffId}:{w:Workspace;clientId?:string;staffId?:string}){const rows=w.appointments.filter(a=>(!clientId||a.client_id===clientId)&&(!staffId||a.staff_id===staffId)).sort((a,b)=>b.starts_at.localeCompare(a.starts_at));return <section><h2>История записей</h2>{rows.length?rows.map(a=><div className="history-row" key={a.id}><strong>{localDay(a.starts_at,w.organization.timezone)} · {localTime(a.starts_at,w.organization.timezone)}</strong><p>{w.services.find(s=>s.id===a.service_id)?.name} · {w.staff.find(s=>s.id===a.staff_id)?.display_name}</p><span>{statusLabels[a.status]} · {money(a.price_minor,w.organization.currency)}</span></div>):<p className="muted">Визитов ещё не было.</p>}</section>;}
export default function Clients(){const state=useWorkspace();const [query,setQuery]=useState(''),[archived,setArchived]=useState(false);return <><PageHeading eyebrow="CRM · люди и история" title="Клиенты" description="Всё, что помогает заботиться о гостях и видеть их историю."/><Gate state={state}>{w=>{const rows=w.clients.filter(c=>!!c.archived_at===archived&&`${c.full_name} ${c.phone||''} ${c.email||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));return <><div className="toolbar"><Sheet title="Новый клиент" trigger={<button className="btn">Добавить клиента</button>}>{close=><Form onSubmit={async values=>{await mutate({table:'clients',values});close();await state.refresh();}}><ClientFields/></Form>}</Sheet><label className="field"><span>Поиск</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Имя, телефон или email"/></label><label className="check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Архив</label></div><p className="muted">Найдено: {rows.length}</p><div className="crm-list">{rows.map(c=>{const m=clientMetrics(w,c.id);return <Sheet key={c.id} title={c.full_name} trigger={<button className="crm-card client-card"><span className="avatar">{c.full_name.slice(0,1)}</span><span className="grow"><strong>{c.full_name}</strong><span className="muted">{c.phone||'Телефон не указан'}</span><span className="muted">{m.visits} визитов · {m.last?localDay(m.last,w.organization.timezone):'Первый визит впереди'}</span></span><span className="money">{money(m.ltv,w.organization.currency)}<small>LTV</small></span></button>}>{close=><><div className="detail-metrics"><span>{m.visits} визитов</span><span>LTV {money(m.ltv,w.organization.currency)}</span></div>{!c.archived_at&&<Link className="btn" href={`/appointments?client=${c.id}`}>Записать клиента</Link>}<Form onSubmit={async values=>{await mutate({table:'clients',id:c.id,values:{...values,vip:c.vip}});close();await state.refresh();}}><ClientFields client={c}/></Form><History w={w} clientId={c.id}/>{!c.archived_at&&<Archive onArchive={async()=>{await mutate({table:'clients',id:c.id,operation:'archive'});close();await state.refresh();}}/>}</>}</Sheet>;})}</div>{!rows.length&&<Empty title={query?'Клиент не найден':archived?'Архив пуст':'Ваш первый гость'} text="Добавьте клиента, чтобы записать его на услугу и сохранить историю визитов."/>}</>;}}</Gate></>;}
