'use client';
import { PageHeading } from '@/components/page-heading';
import { Archive, Field, Form, Gate, MoreLinks, Sheet, mutate, useWorkspace } from './shared';
import type { Branch, Workspace } from '@/lib/domain/types';
function BranchForm({ b, w, saved }: { b?: Branch; w: Workspace; saved: () => Promise<void> }) {
  return <Form onSubmit={async values => { await mutate({ table: 'branches', id: b?.id, values: { ...values, timezone: w.organization.timezone } }); await saved(); }}><Field label="Название филиала" name="name" required value={b?.name} /><Field label="Адрес" name="address" value={b?.address} maxLength={300} /><Field label="Телефон" name="phone" type="tel" value={b?.phone} /><p className="muted">Расписание всех филиалов использует часовой пояс салона: {w.organization.timezone}.</p></Form>;
}
export default function Settings() {
  const state = useWorkspace();
  return <><PageHeading title="Настройки" eyebrow="Салон · доступ" description="Организация, филиалы и права команды." /><MoreLinks /><Gate state={state} operator={false}>{w => <>
    <section className="crm-card"><h2 className="text-xl font-extrabold">{w.organization.name}</h2><p className="muted">Роль: {w.role} · {w.organization.currency} · {w.organization.timezone}</p><p className="muted">Telegram ID: {w.user.telegram_user_id}</p></section>
    {w.role === 'owner' && <><Sheet title="Организация" trigger={<button className="btn mt-4">Изменить салон</button>}>{close => <Form onSubmit={async values => { await mutate({ operation: 'organization', values }, '/api/operations'); close(); await state.refresh(); }}><Field label="Название салона" name="name" required value={w.organization.name} /><Field label="Часовой пояс IANA" name="timezone" required value={w.organization.timezone} /><p className="muted">Валюта учёта фиксирована. Часовой пояс нельзя менять после появления смен или записей.</p></Form>}</Sheet>
      <h2 className="mt-5 text-xl font-extrabold">Филиалы</h2><div className="crm-list">{w.branches.filter(b => !b.archived_at).map(b => <Sheet title={b.name} key={b.id} trigger={<button className="crm-card client-card"><span className="grow"><strong>{b.name}</strong><span className="muted">{b.address || 'Адрес не указан'}</span></span></button>}>{close => <><BranchForm w={w} b={b} saved={async () => { close(); await state.refresh(); }} /><Archive onArchive={async () => { await mutate({ table: 'branches', id: b.id, operation: 'archive' }); close(); await state.refresh(); }} /></>}</Sheet>)}</div>
      <Sheet title="Новый филиал" trigger={<button className="btn secondary">Добавить филиал</button>}>{close => <BranchForm w={w} saved={async () => { close(); await state.refresh(); }} />}</Sheet>
      <h2 className="mt-5 text-xl font-extrabold">Доступ команды</h2><p className="muted">Добавляйте только известный Telegram ID. Участник сначала должен открыть приложение через бота.</p><Form label="Добавить участника" onSubmit={async values => { await mutate({ operation: 'member', values }, '/api/operations'); await state.refresh(); }}><Field label="Telegram ID" name="telegram_user_id"><input name="telegram_user_id" inputMode="numeric" pattern="[0-9]{1,16}" required /></Field><Field label="Роль" name="role"><select name="role"><option value="specialist">Специалист</option><option value="admin">Администратор</option><option value="owner">Владелец</option></select></Field></Form>
      <div className="crm-list">{w.members.map(m => <Sheet key={m.user_id} title="Права участника" trigger={<button className="crm-card client-card"><span className="grow">{m.user_id === w.user.id ? 'Вы' : w.staff.find(s => s.user_id === m.user_id)?.display_name || m.user_id}<span className="muted">{m.role}</span></span></button>}>{close => <Form onSubmit={async v => { await mutate({ operation: 'member_role', values: { ...v, user_id: m.user_id } }, '/api/operations'); close(); await state.refresh(); }}><Field label="Роль" name="role"><select name="role" defaultValue={m.role}><option value="specialist">Специалист</option><option value="admin">Администратор</option><option value="owner">Владелец</option></select></Field><p className="muted">Последний владелец защищён от понижения роли на уровне базы данных.</p></Form>}</Sheet>)}</div></>}
    <section className="crm-card mt-5"><h2 className="text-xl font-extrabold">Telegram</h2><p className="muted">Доступ к данным подтверждён серверной сессией. Для проверки запуска, клавиатуры и безопасных отступов откройте приложение в Telegram на устройстве. Онлайн-эквайринг и автоматические напоминания не подключены.</p></section>
  </>}</Gate></>;
}
