'use client';
import { useCallback, useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { Dialog, AlertDialog } from 'radix-ui';
import { X, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import type { Workspace } from '@/lib/domain/types';
export async function mutate(body:unknown,endpoint='/api/workspace'){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.fields?Object.entries(data.fields).map(([k,v])=>`${k}: ${(v as string[]).join(', ')}`).join('; '):data.error||'Не удалось сохранить');return data;}
export function useWorkspace(){const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const refresh=useCallback(async()=>{try{const r=await fetch('/api/workspace',{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body);setError('');}catch(e){setError(e instanceof Error?e.message:'Сеть недоступна');}finally{setLoading(false);}},[]);useEffect(()=>{const controller=new AbortController();fetch('/api/workspace',{cache:'no-store',signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body);setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(String(e.message));setLoading(false);}});window.addEventListener('atelier-session-ready',refresh);return()=>{controller.abort();window.removeEventListener('atelier-session-ready',refresh);};},[refresh]);return {data,error,loading,refresh};}
export function Gate({state,children,operator=true}:{state:ReturnType<typeof useWorkspace>;children:(w:Workspace)=>ReactNode;operator?:boolean}){if(state.error)return <section className="crm-card empty" role="alert"><h2>Данные недоступны</h2><p>{state.error}</p><button className="btn" onClick={state.refresh}>Повторить</button><Link className="btn secondary" href="/onboarding">Создать салон</Link></section>;if(!state.data)return <div className="crm-card empty" role="status">Загружаем ваш салон…</div>;if(operator&&state.data.role==='specialist')return <div className="crm-card empty"><h2>Доступ для администратора</h2><p>Ваша роль — специалист. Собственные записи доступны в расписании.</p><Link className="btn" href="/appointments">Мои записи</Link></div>;return children(state.data);}
export function Sheet({title,trigger,children}:{title:string;trigger:ReactNode;children:(close:()=>void)=>ReactNode}){const [open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const back=window.Telegram?.WebApp?.BackButton;if(!back)return;const close=()=>setOpen(false);back.show();back.onClick(close);return()=>{back.offClick(close);back.hide();};},[open]);return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild>{trigger}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet"><div className="sheet-head"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>Atelier · изменения сохраняются в вашем салоне</Dialog.Description></div><Dialog.Close className="icon-btn" aria-label="Закрыть"><X/></Dialog.Close></div>{open&&children(()=>setOpen(false))}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Form({children,onSubmit,label='Сохранить'}:{children:ReactNode;onSubmit:(values:Record<string,string>)=>Promise<void>;label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef<HTMLDivElement>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;setBusy(true);setError('');try{await onSubmit(values);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');requestAnimationFrame(()=>ref.current?.focus());}finally{setBusy(false);}}return <form className="crm-form" onSubmit={submit}><div role={error?'alert':undefined} tabIndex={-1} ref={ref}>{error&&<p className="error-message">{error}</p>}</div><fieldset disabled={busy}>{children}</fieldset><button className="btn" disabled={busy} type="submit">{busy?'Сохраняем…':label}</button></form>;}
export function Field({label,name,value='',type='text',required=false,maxLength=120,children}:{label:string;name:string;value?:string|number|null;type?:string;required?:boolean;maxLength?:number;children?:ReactNode}){return <label className="field"><span>{label}{required?' *':''}</span>{children||(type==='textarea'?<textarea name={name} defaultValue={value??''} maxLength={maxLength} rows={3}/>:<input name={name} type={type} defaultValue={value??''} required={required} maxLength={maxLength} step={type==='number'?'1':undefined}/>)}</label>;}
export function Empty({title='Здесь пока ничего нет',text='Добавьте первую запись — только реальные данные, без демонстрационных цифр.'}:{title?:string;text?:string}){return <div className="crm-card empty"><h2>{title}</h2><p>{text}</p></div>;}
export function Archive({onArchive}:{onArchive:()=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);return <AlertDialog.Root open={open} onOpenChange={setOpen}><AlertDialog.Trigger className="btn danger secondary">Архивировать</AlertDialog.Trigger><AlertDialog.Portal><AlertDialog.Overlay className="sheet-overlay"/><AlertDialog.Content className="confirm"><AlertDialog.Title>Архивировать запись?</AlertDialog.Title><AlertDialog.Description>История визитов и платежей останется. Объект больше нельзя будет выбрать для новой записи.</AlertDialog.Description>{error&&<p role="alert">{error}</p>}<div className="actions"><AlertDialog.Cancel className="btn secondary" disabled={busy}>Оставить</AlertDialog.Cancel><button className="btn danger" disabled={busy} onClick={async()=>{setBusy(true);try{await onArchive();setOpen(false);}catch(e){setError(String(e));}finally{setBusy(false);}}}>Архивировать</button></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>;}
export function MoreLinks(){return <div className="crm-grid">{([['/services','Услуги'],['/staff','Команда'],['/analytics','Аналитика'],['/settings','Настройки']] as const).map(([href,label])=><Link className="crm-card shortcut" key={href} href={href}>{label}<ArrowRight size={20}/></Link>)}</div>;}
